version: "3.3"
services:

  cvd-predictor:
    build: .
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: 5001
      VIRTUAL_HOST: cvd-predictor.137.120.31.148.nip.io
      LETSENCRYPT_HOST: cvd-predictor.137.120.31.148.nip.io
    volumes:
      - ./:/app/
    # ports:
    #   - 5001:5001